### ISSUE TITLE
`bind_env` is not respected when retrieving a nested key's parent.

### ISSUE THREAD

**Issue by jperkelens** [admiralobvious/vyper#6]
Ex.

config.yml
```yml
   db:
      host: localhost
      port: 5432
```

app.py
```python
print(os.getenv('PSQL_ENDPOINT')) # prints dev-server
v.read_in_config()
v.automatic_env()
v.bind_env('db.host', 'PSQL_ENDPOINT')
print(v.get('db.host')) # prints dev-server
print(v.get('db')) #prints {host: localhost, port: 5432}
```
