### ISSUE TITLE
Complex keys are returning all lower case.

### ISSUE THREAD

**Issue by jperkelens** [admiralobvious/vyper#9]
Hi! I'm not sure if this is an unintended side effect of the PR i merged in, but v0.2.0 returns complex config objects with all lower case keys. Ex.

app_config.yml
```yaml
job_config:
  Name: cluster_name
  AdditionalInfo:
      key1: val1
```

```python
import vyper as v
# Assume config setup
print(v.get('job_config'))
```

This prints: `{'name': 'cluster_name', 'additionalinfo': { 'key1': 'val1' } }`

This is less than ideal because im storing an EMR job config in vyper and `boto3`'s kwargs are all in camel case.
